### ISSUE TITLE
Uploading media

### ISSUE THREAD

**Issue by ZangievM** [Automattic/android-wordpress-com-rest#20]
Is it possible to upload media to blog with this sdk?
I use this "https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/media/new/" api reference.
And also use OkHttp. And I can not upload media.. Request code is 404.
This is my code:

            String URL = "https://public-api.wordpress.com/rest/v1.2/sites/zangievblog.wordpress.com/media/new";
            RequestBody requestBody = new MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("media","0")                   .addFormDataPart("media","file.jpg",RequestBody.create(MediaType.parse("image/jpeg"),file1))
                    .build();
            OkHttpClient client = new OkHttpClient();

            final okhttp3.Request request = new okhttp3.Request.Builder()
                    .addHeader("Authorization", "Bearer 0(t0Pkv%YpN^F6xmZN*&@Zok(h9^5!@(vB6KD1qeJci6xvGvjuNvvf7lqL4s$xBw")
                    .addHeader("Content-Type","application/x-www-form-urlencoded")
                    .url(URL)
                    .post(requestBody)
                    .build();

**Comment by hypest** [comment]
Hey @ZangievM 👋

Sorry this ticket went unattended to for so long. The project is not maintained anymore and that made the ticket go unnoticed. Hope we can help some more on any of our active projects instead.

Apologies and thank you for reaching out!
